name: CMake Test

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - { id: ubuntu-gcc, platform: ubuntu, cc: gcc, cpp: g++ }

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ matrix.cfg.id }}
          file: tests/docker/${{ matrix.cfg.platform }}.Dockerfile
          build-args: |
            cc=${{ matrix.cfg.cc }}
            cxx=${{ matrix.cfg.cpp }}
            setup_options=${{ matrix.cfg.setup_options }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Compiler Cache
        id: ccache
        uses: actions/cache@v4
        with:
          path: ccache
          key: ${{ matrix.cfg.id }}-ccache
      - name: Start Docker container
        run: |
            docker run ${{ matrix.cfg.id }} -d --name ${{ matrix.cfg.id }} sleep infinity
      - name: Build cps-config
        run: |
          docker exec ${{ matrix.cfg.id }} \
          -e CC="ccache ${{ matrix.cfg.cc }}" -e CXX="ccache ${{ matrix.cfg.cpp }}" \
          -e CCACHE_DIR="/ccache" \
          --mount=type=bind,source=ccache,target=/ccache \
          --mount=type=bind,source=ccache,target=/workdir \
          cmake -S /workdir -B /build/ --preset default && cmake --build build --config RelWithDebInfo
      - name: Run tests
        run: |
          docker exec ${{ matrix.cfg.id }} ctest --test-dir /build
      - name: Stop Docker container
        run: |
          docker stop ${{ matrix.cfg.id }}
